{
    "name": "Maintenance du parc automobile",
    "summary": "Planifier, suivre et automatiser les maintenances preventives et curatives des vehicules",
    "version": "1.0.0",
    "category": "Operations/Fleet",
    "website": "https://example.com",
    "author": "Equipe Maintenance Digitale",
    "license": "OEEL-1",
    "depends": [
        "fleet",
        "maintenance",
        "stock",
        "purchase",
        "mail",
        "calendar",
        "web",
        "base_automation",
        "custom_fleet_management",
    ],
    "data": [
        "security/fleet_groups.xml",
        "security/ir.model.access.csv",
        "security/fleet_security.xml",
        "data/fleet_sequences.xml",
        "data/mail_template_fleet.xml",
        "data/fleet_cron.xml",
        "data/fleet_automated_actions.xml",
        "views/fleet_vehicle_views.xml",
        "views/fleet_maintenance_plan_views.xml",
        "views/fleet_maintenance_intervention_views.xml",
        "views/fleet_maintenance_request_wizard_views.xml",
        "views/res_config_settings_views.xml",
        "views/fleet_dashboard.xml",
        "views/fleet_menu.xml",
        "report/maintenance_intervention_report.xml",
        "report/maintenance_kpi_report.xml",
    ],
    "demo": [],
    "application": True,
}
