{
    'name': 'Personnalisation des rapports PDF',
    'summary': 'Summery',
    'description': 'Le module permet de personnaliser les rapports PDF',
    'category': 'Sales/account',
    'author': 'Alexandre Koua',
    'company': 'Partenaires Succes',
    'maintainer': 'Alexandre Koua',
    'website': "https://www.partenairesucces.com/",
    'license': 'AGPL-3',
    'depends': [
        'product',
        'stock',
        'stock_account',
        'custom_stock',
    ],
    'data': [
        'security/ir.model.access.csv',
        'wizard/stock_valorise_report_wizard_views.xml',
        'report/stock_picking_report_template.xml',
        'wizard/sale_stat_report_wizard_view.xml',
        'report/report_sale_stat_template.xml',
        'wizard/reception_fournisseur_wizard_views.xml',
        'report/report_reception_fournisseur_template.xml',
        'wizard/suplier_report_return_wizard.xml',
        'report/report_suplier_return_template.xml',
        'wizard/cumul_inventary_report_wizard.xml',
        'report/report_cumul_inventary_template.xml',
        'wizard/stock_adjustment_report_wizard.xml',
        'report/report_stock_scrap_template.xml',
        'wizard/report_daily_sales_wizard_view.xml',
        'report/report_daily_sales_template.xml',
    ],
    'installable': True,
    'auto_install': False
}
