# -*- coding: utf-8 -*-
{
    "name": "Custom Fleet Fuel Management",
    "summary": "Gestion des cartes carburant, recharges, dépenses et KPI pour le parc auto",
    "version": "1.0.0",
    "category": "Fleet",
    "website": "https://example.com",
    "author": "Custom Fleet Team",
    "license": "OEEL-1",
    "depends": [
        "base",
        "fleet",
        "hr",
        "account",
        "account_budget",
        "analytic",
        "mail",
        "board",
        "custom_fleet_management",
        "custom_fleet_maintenance",
    ],
    "data": [
        "security/fleet_fuel_groups.xml",
        "security/ir.model.access.csv",
        "security/fleet_fuel_rules.xml",
        "data/fleet_fuel_sequences.xml",
        "data/fleet_fuel_cron.xml",
        "data/mail_template_fleet_fuel.xml",
        "views/fleet_fuel_card_views.xml",
        "views/fleet_fuel_recharge_views.xml",
        "views/fleet_fuel_expense_views.xml",
        "views/fleet_fuel_expense_batch_views.xml",
        "views/fleet_fuel_summary_views.xml",
        "views/res_config_settings_views.xml",
        "views/fleet_fuel_analytics_views.xml",
        "views/fleet_fuel_dashboard.xml",
        "views/fleet_menu.xml",
        "report/fleet_fuel_reports.xml",
        "report/fleet_fuel_statement.xml",
        "report/fleet_fuel_summary_report.xml",
    ],
    "demo": [
        "tests/demo_fleet_fuel.xml",
    ],
    "application": True,
    "installable": True,
}
